DELETE FROM ATHRESULT.AREA;
INSERT INTO ATHRESULT.AREA(AREA_CODE, AREA_NAME) VALUES ('EUR', 'Europe');
INSERT INTO ATHRESULT.AREA(AREA_CODE, AREA_NAME) VALUES ('ASI', 'Asia');
INSERT INTO ATHRESULT.AREA(AREA_CODE, AREA_NAME) VALUES ('AFR', 'Africa');
INSERT INTO ATHRESULT.AREA(AREA_CODE, AREA_NAME) VALUES ('NOA', 'North America');
INSERT INTO ATHRESULT.AREA(AREA_CODE, AREA_NAME) VALUES ('SOA', 'South America');
INSERT INTO ATHRESULT.AREA(AREA_CODE, AREA_NAME) VALUES ('OCE', 'Oceania');

DELETE FROM ATHRESULT.COUNTRY;
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('TUR', 'Türkiye', 'EUR');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('USA', 'United States', 'NOA');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('JAM', 'Jamaica', 'NOA');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('GBR', 'United Kingdom', 'EUR');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('GER', 'Germany', 'EUR');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('ITA', 'Italy', 'EUR');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('FRA', 'France', 'EUR');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('CHN', 'China', 'ASI');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('MRK', 'Morocco', 'AFR');
INSERT INTO ATHRESULT.COUNTRY(COUNTRY_CODE, COUNTRY_NAME, AREA_CODE) VALUES ('BRA', 'Brazil', 'SOA');